from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from catley.game.actions.base import GameIntent
    from catley.util.coordinates import WorldTilePos


@dataclass
class PathfindingGoal:
    """
    Represents an actor's autonomous movement goal.

    This is a stateful object that holds the final destination and a
    disposable, cached path to get there. The path is treated as a
    suggestion and can be invalidated and recalculated if obstacles appear.

    Attributes:
        target_pos: The final destination tile for the movement.
        final_intent: An optional GameIntent to be queued upon arrival.
        _cached_path: A list of tiles representing the current suggested
                      route. This is considered a private cache and can be
                      discarded and regenerated by the movement logic.
    """

    target_pos: WorldTilePos
    final_intent: GameIntent | None = None
    _cached_path: list[WorldTilePos] | None = None
