"""Deterministic display-name generation for NPCs."""

from __future__ import annotations

from typing import TYPE_CHECKING

from brileta.game.actors.identity import Gender, NPCIdentity
from brileta.util import rng

if TYPE_CHECKING:
    from collections.abc import Callable, MutableSet

    from brileta.game.actors.npc_core import NPCType

_name_rng = rng.get("world.npc_names")

# Authored, Brileta-native names.
# Given names are separated by gender for the NPC identity system.
_MALE_GIVEN_NAMES: tuple[str, ...] = (
    "Aaron",
    "Adam",
    "Alan",
    "Albert",
    "Alfred",
    "Allen",
    "Andrew",
    "Anthony",
    "Benjamin",
    "Bernard",
    "Blake",
    "Brian",
    "Bruce",
    "Caleb",
    "Calvin",
    "Carl",
    "Charles",
    "Christopher",
    "Colin",
    "Daniel",
    "David",
    "Dean",
    "Dennis",
    "Donald",
    "Douglas",
    "Edgar",
    "Edward",
    "Edwin",
    "Elliot",
    "Ellis",
    "Emmett",
    "Ernest",
    "Ethan",
    "Eugene",
    "Evan",
    "Francis",
    "Frank",
    "Frederick",
    "Gabriel",
    "George",
    "Gerald",
    "Gilbert",
    "Gordon",
    "Graham",
    "Gregory",
    "Harold",
    "Harry",
    "Harvey",
    "Henry",
    "Howard",
    "Hugh",
    "Isaac",
    "Jack",
    "Jacob",
    "James",
    "Jason",
    "Joel",
    "John",
    "Jonathan",
    "Joseph",
    "Kenneth",
    "Lawrence",
    "Leon",
    "Leonard",
    "Lewis",
    "Louis",
    "Lucas",
    "Mark",
    "Martin",
    "Matthew",
    "Maxwell",
    "Michael",
    "Miles",
    "Nathan",
    "Nicholas",
    "Noah",
    "Norman",
    "Oliver",
    "Oscar",
    "Owen",
    "Patrick",
    "Paul",
    "Peter",
    "Philip",
    "Raymond",
    "Richard",
    "Robert",
    "Roger",
    "Russell",
    "Samuel",
    "Scott",
    "Simon",
    "Stephen",
    "Thomas",
    "Timothy",
    "Vincent",
    "Walter",
    "Warren",
    "Wesley",
    "William",
)

_FEMALE_GIVEN_NAMES: tuple[str, ...] = (
    "Abigail",
    "Ada",
    "Alice",
    "Amelia",
    "Amy",
    "Anna",
    "Anne",
    "Audrey",
    "Barbara",
    "Beatrice",
    "Beth",
    "Betty",
    "Caroline",
    "Catherine",
    "Clara",
    "Claire",
    "Cora",
    "Diana",
    "Donna",
    "Dorothy",
    "Edith",
    "Elaine",
    "Eleanor",
    "Elise",
    "Ellen",
    "Emily",
    "Emma",
    "Esther",
    "Eva",
    "Evelyn",
    "Florence",
    "Frances",
    "Gail",
    "Georgia",
    "Grace",
    "Hannah",
    "Harriet",
    "Hazel",
    "Helen",
    "Ida",
    "Irene",
    "Isabel",
    "Jane",
    "Janet",
    "Jean",
    "Joan",
    "Josephine",
    "Joyce",
    "Judith",
    "Julia",
    "June",
    "Karen",
    "Kate",
    "Katherine",
    "Kathleen",
    "Laura",
    "Leah",
    "Lena",
    "Lillian",
    "Linda",
    "Lois",
    "Louise",
    "Louisa",
    "Lucy",
    "Lydia",
    "Mabel",
    "Mae",
    "Margaret",
    "Maria",
    "Marie",
    "Martha",
    "Mary",
    "Matilda",
    "Miriam",
    "Molly",
    "Nancy",
    "Naomi",
    "Nora",
    "Olive",
    "Patricia",
    "Pearl",
    "Rachel",
    "Rebecca",
    "Rita",
    "Rose",
    "Ruth",
    "Sarah",
    "Selma",
    "Sophia",
    "Stella",
    "Susan",
    "Sylvia",
    "Teresa",
    "Thea",
    "Vera",
    "Victoria",
    "Viola",
    "Vivian",
    "Wendy",
    "Winifred",
)

_SURNAME_PREFIXES: tuple[str, ...] = (
    "Abb",
    "Ack",
    "Add",
    "Ald",
    "All",
    "Ander",
    "Ash",
    "At",
    "Back",
    "Baker",
    "Bar",
    "Barn",
    "Barr",
    "Beech",
    "Bell",
    "Ben",
    "Black",
    "Bloom",
    "Bond",
    "Brad",
    "Brook",
    "Brown",
    "Buck",
    "Bur",
    "Burns",
    "Butler",
    "Car",
    "Carr",
    "Cart",
    "Chad",
    "Chap",
    "Clark",
    "Clay",
    "Cole",
    "Cook",
    "Coop",
    "Cross",
    "Dale",
    "Day",
    "Dean",
    "Dell",
    "East",
    "Ell",
    "Farm",
    "Field",
    "Finch",
    "Fish",
    "Ford",
    "Fore",
    "Foster",
    "Frank",
    "Green",
    "Hall",
    "Ham",
    "Hart",
    "Hay",
    "Heath",
    "Hill",
    "Hol",
    "Hunt",
    "King",
    "Lake",
    "Lane",
    "Lee",
    "Little",
    "Long",
    "Marsh",
    "Mason",
    "May",
    "Mill",
    "Moore",
    "Nash",
    "North",
    "Oak",
    "Page",
    "Park",
    "Payne",
    "Perry",
    "Pike",
    "Porter",
    "Price",
    "Reed",
    "Rich",
    "Ross",
    "Row",
    "Shaw",
    "Shepherd",
    "Short",
    "Smith",
    "South",
    "Stone",
    "Taylor",
    "Under",
    "Ward",
    "Warren",
    "West",
    "Whit",
    "Wood",
    "Wright",
    "Young",
)

_SURNAME_SUFFIXES: tuple[str, ...] = (
    "acre",
    "bank",
    "bar",
    "beck",
    "bell",
    "bend",
    "bridge",
    "berry",
    "brook",
    "burn",
    "bury",
    "by",
    "clay",
    "cliff",
    "coate",
    "comb",
    "croft",
    "cross",
    "dale",
    "den",
    "ditch",
    "don",
    "down",
    "ell",
    "end",
    "er",
    "ett",
    "fax",
    "fell",
    "field",
    "ford",
    "forth",
    "gate",
    "grove",
    "hall",
    "ham",
    "hard",
    "hart",
    "haw",
    "hay",
    "head",
    "hill",
    "hope",
    "house",
    "hurst",
    "ing",
    "kin",
    "lake",
    "land",
    "lane",
    "ley",
    "lin",
    "lock",
    "low",
    "man",
    "mark",
    "marsh",
    "mead",
    "mere",
    "mill",
    "mont",
    "moor",
    "more",
    "mouth",
    "nell",
    "ner",
    "ness",
    "net",
    "old",
    "over",
    "park",
    "path",
    "pool",
    "port",
    "ridge",
    "row",
    "shaw",
    "shire",
    "side",
    "smith",
    "son",
    "stead",
    "stone",
    "street",
    "thorn",
    "ton",
    "tree",
    "vale",
    "wall",
    "ward",
    "water",
    "way",
    "well",
    "white",
    "wick",
    "win",
    "wood",
    "worth",
    "wright",
    "yard",
)


def generate_npc_name(
    npc_type: NPCType,
    used_names: MutableSet[str],
    identity: NPCIdentity | None = None,
) -> str:
    """Return a deterministic display name suitable for ``npc_type``.

    Identity-bearing social NPCs get full names. Other identity-bearing NPCs get
    given names. Creatures without identity use the archetype display name.
    """
    if identity is None:
        return npc_type.display_name

    gender = identity.gender
    if _uses_full_human_name(npc_type):
        return generate_human_name(gender, used_names)

    return generate_given_name(gender, used_names)


def generate_human_name(gender: Gender, used_names: MutableSet[str]) -> str:
    """Return a unique human full name for the requested gender."""
    return _unique_name(lambda: _human_full_name(gender), used_names)


def generate_given_name(gender: Gender, used_names: MutableSet[str]) -> str:
    """Return a unique given name for the requested gender."""
    return _unique_name(
        lambda: _name_rng.choice(_given_names_for_gender(gender)), used_names
    )


def _uses_full_human_name(npc_type: NPCType) -> bool:
    """Return whether ``npc_type`` should receive a surname."""
    return "social" in npc_type.tags or "routine" in npc_type.tags


def _human_full_name(gender: Gender) -> str:
    given_names = _given_names_for_gender(gender)
    given_name = _name_rng.choice(given_names)
    surname = (
        f"{_name_rng.choice(_SURNAME_PREFIXES)}{_name_rng.choice(_SURNAME_SUFFIXES)}"
    )
    return f"{given_name} {surname}"


def _given_names_for_gender(gender: Gender) -> tuple[str, ...]:
    if gender is Gender.MALE:
        return _MALE_GIVEN_NAMES
    return _FEMALE_GIVEN_NAMES


def _unique_name(make_candidate: Callable[[], str], used_names: MutableSet[str]) -> str:
    """Draw until a unique name is found, then reserve it in ``used_names``."""
    max_attempts = 128
    for _ in range(max_attempts):
        candidate = make_candidate()
        if candidate not in used_names:
            used_names.add(candidate)
            return candidate

    # Exhaustion is unlikely for residents but possible for short one-word pools.
    # Keep the fallback readable and stable.
    while True:
        candidate = f"{make_candidate()} {len(used_names) + 1}"
        if candidate not in used_names:
            used_names.add(candidate)
            return candidate
